name: Christian Zirnig
favicon: null
layout_spectrum: 0.9546035521198064
typography_spectrum: 0.3345596226863563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.47913852194324136
  lightness: 0.1622520114760846
  saturation: 0.86761738313362
  rhythmicContrast: 0.9694857394788414
purpose: []
